# -*- coding: utf-8 -*-
"""Livreur (Réception et confirmation)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_R7AAcmHWkmId0h_ul9VXUcI73iQubAH
"""

# -*- coding: utf-8 -*-
import time, orjson, redis, random, sys, os

# --- CONFIG ---
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))

# --- INITIALISATION ---
courier_id = sys.argv[1] if len(sys.argv) > 1 else f"c{random.randint(100,999)}"

# On utilise decode_responses=False pour orjson, mais on décode manuellement pour les clés
r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, decode_responses=False)
ps = r.pubsub()

ps.subscribe("jobs")
ps.psubscribe(f"assignment:{courier_id}") # On écoute seulement les assignations qui nous concernent

print(f"🚴 [{courier_id}] En écoute des nouvelles courses... (Ctrl+C pour quitter)")

def repondre_interet(job):
    """Envoie un message d'intérêt pour une course sur le canal dédié."""
    job_id = job["job_id"]
    payload = {
        "job_id": job_id,
        "courier_id": courier_id,
        "eta": random.randint(4, 12),
        "sent_at": time.time()
    }
    # Publie l'intérêt pour que le manager le reçoive
    r.publish(f"interest:{job_id}", orjson.dumps(payload))
    print(f"📨 [{courier_id}] Intérêt envoyé pour la course {job_id}.")

def confirmer_recuperation(job_id):
    """Confirme au manager que la commande a été récupérée."""
    payload = {"job_id": job_id, "courier_id": courier_id, "status": "picked_up", "timestamp": time.time()}
    r.publish("pickup_confirmations", orjson.dumps(payload))
    print(f"🛍️  [{courier_id}] Commande {job_id} récupérée. En route pour la livraison.")

def confirmer_livraison(job_id):
    """Confirme au manager que la commande a été livrée."""
    payload = {"job_id": job_id, "courier_id": courier_id, "status": "delivered", "timestamp": time.time()}
    r.publish("delivery_confirmations", orjson.dumps(payload))
    print(f"🏁 [{courier_id}] Commande {job_id} livrée avec succès !")

def a_deja_un_livreur(job_id: str) -> bool:
    """Vérifie si la course a déjà un livreur assigné dans son HASH."""
    # On doit décoder la clé pour la comparaison
    courier_assigned = r.hget(f"job:{job_id}", "courier_id")
    return courier_assigned is not None and courier_assigned.decode('utf-8') != ""

def boucle_principale():
    """Écoute les messages et gère le cycle de vie de la course pour le livreur."""
    current_job_id = None

    try:
        while True:
            # Écoute des messages sur les canaux souscrits
            msg = ps.get_message(ignore_subscribe_messages=True, timeout=0.1)

            if not msg:
                time.sleep(0.05)
                continue

            channel = msg['channel'].decode('utf-8')
            data = orjson.loads(msg['data'])

            # --- CAS 1: Nouvelle course publiée sur le canal 'jobs' ---
            if channel == "jobs":
                job_id = data["job_id"]
                # Si le livreur est déjà sur une course, il ignore les nouvelles
                if current_job_id:
                    continue

                print("\n🍽️  Nouvelle course disponible")
                print(f"  • ID : {job_id}")
                print(f"  • Rétribution : {data['fee']} €")

                if a_deja_un_livreur(job_id):
                    print("⛔ Course déjà attribuée.")
                else:
                    choix = input("Accepter cette course ? (o/n) : ").strip().lower()
                    if choix == "o":
                        repondre_interet(data)
                    else:
                        print(f"ℹ️ [{courier_id}] Course ignorée.")

            # --- CAS 2: Assignation reçue sur le canal personnel ---
            elif channel == f"assignment:{courier_id}":
                job_id = data["job_id"]
                if data.get("courier_id") == courier_id:
                    print(f"\n✅ [{courier_id}] Vous avez été sélectionné pour {job_id} !")
                    current_job_id = job_id

                    # Logique de confirmation
                    time.sleep(random.uniform(3, 6)) # Simule le temps pour aller au restaurant
                    input("Appuyez sur Entrée pour confirmer la récupération de la commande...")
                    confirmer_recuperation(current_job_id)

                    time.sleep(random.uniform(5, 10)) # Simule le temps de livraison
                    input("Appuyez sur Entrée pour confirmer la livraison chez le client...")
                    confirmer_livraison(current_job_id)

                    # La course est terminée, le livreur est de nouveau disponible
                    print(f"\n🎉 [{courier_id}] Mission accomplie. En attente de nouvelles courses.")
                    current_job_id = None

    except KeyboardInterrupt:
        print(f"\n🛑 [{courier_id}] Arrêt du livreur.")
    finally:
        ps.close()

if __name__ == "__main__":
    boucle_principale()